spring:
  application:
    name: spring-boot-eureka-consumer-client-rest-api


server:
  port: 8084

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka